#!/usr/bin/env python3

from fsa import FSA, build_trie
from fst import FST
import json


def build_editfst(alphabet, counts):
    """Build a weighted FST instance that implements one-edit-distance operations.

    You should use the add_transition() method of the FST class
    to build an FST that returns all misspellings of a word
    with one-edit-distance away.

    The transition weight should be set based on the number of times
    particular edit operations were observed in the data (e.g.,
    spelling-data.txt). You are recommended to estimate (smoothed)
    probabilities for each edit operation, and use its logarithm.
    You are free to experiment with weighting schemes, but remember
    that the transduce() method of FST assumes additive weights.

    Arguments:
    ----
    alphabet    All letters that we should recognize
    counts      Counts generated by compute-weights.py
    """


if __name__ == "__main__":

    ## Example usage
    with open('lexicon.txt', 'rt') as f:
        words = f.read().strip().split()
    with open('spell-errors.json', 'rt') as f:
        errcount = json.loads(f.read())

    # Build the trie lexicon
    fsa = build_trie(words)
    # Minimize it
    fsa.minimize()
    # Convert it to an FST
    lexicon = FST.fromfsa(fsa)
    # Build the edit-distance FST
    edits = build_editfst(letters, errcount)
    # Compose them
    spellfst = FST.compose_fst(lexicon, edits)
    # The above generates all spelling mistakes, we want the invert
    spellfst.invert()
    for sperr, w in sorted(spellfst.transduce("wort"),
                           key=lambda x: x[1], reverse=True):
        print(sperr, w)
